---
title: "NYC Sanitation and Rat Sightings "
author: "Pratishta Yerakala"
date: "4/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Download all necessary libraries 
library(ggplot2)    # the king of plotting 
library(magrittr)   # chain operators, e.g. to "pipe" a value forward
library(plyr)
library(dplyr) 
library(tidyverse)
library(DT)
library(knitr)
library(maps)
library(rgdal)
library(ggmap)
library(tmap)
library(sp)
library(tmap)
library(sf)
library(stars)
library(spData)
library(classInt)
library(lattice)
library(grid)
library(pals)
```


```{r, layout="l-body-outset"}
# read in the main csv file
rat_data<-read.csv("sanitation_data/rat_data.csv")

rat_data <- rat_data %>%
  mutate(Borough = str_to_title(rat_data$Borough))

tonnage_data<-read.csv("sanitation_data/dsny_boro_tonnage.csv", stringsAsFactors = FALSE)


head(rat_data)
head(tonnage_data)
```

converting tonnage month to date data

```{r}
ton_date <- tonnage_data %>%
  mutate(MONTH = paste(MONTH, " / 01")) %>% 
  mutate(MONTH = as.Date(MONTH, format = '%Y / %m / %d')) %>%
  filter(MONTH > as.Date('2020-01-01', '%Y-%m-%d'), MONTH < as.Date('2021-03-01', '%Y-%m-%d')) %>% 
  arrange(desc(MONTH))

ton_date
```
converting and grouping rat data by month and borough

```{r}
rat_date <- rat_data %>% 
  mutate(Created.Date = as.Date(Created.Date, "%m/%d/%Y")) %>%
  mutate(Created.Date = as.character(Created.Date)) %>%
  mutate(Created.Date = substr(Created.Date, 1, 8)) %>%
  mutate(Created.Date = paste(Created.Date, '01')) %>%
  mutate(Created.Date = as.Date(Created.Date, "%Y-%m-%d")) %>%
  group_by(Created.Date, Borough) %>%
  tally() %>%
  filter(Created.Date > as.Date('2020-01-01', '%Y-%m-%d'), Created.Date < as.Date('2021-03-01', '%Y-%m-%d')) %>% 
  arrange(desc(Created.Date))

rat_date
```
```{r}
rat_ton_date <- merge(rat_date, ton_date, by.x = c("Created.Date", "Borough"), by.y = c("MONTH", "BOROUGH")) %>%
  mutate(rate = n / (REFUSETONSCOLLECTED / 100))

rat_ton_date
```
```{r}
p <- ggplot(rat_ton_date, aes(x=Created.Date, y=REFUSETONSCOLLECTED)) +
  geom_line(aes(color = Borough)) +
  geom_point(aes(color = Borough)) +
  xlab("Date by Months") + 
  ylab("Weight of Waste (Tons)")

p
```

```{r}
p <- ggplot(rat_ton_date, aes(x=Created.Date, y=n)) +
  geom_line(aes(color = Borough)) +
  geom_point(aes(color = Borough)) +
  xlab("Date by Months") + 
  ylab("Number of rat sightings")

p
```

```{r}
p <- ggplot(rat_ton_date, aes(x=Created.Date, y=rate)) +
  geom_line(aes(color = Borough)) +
  geom_point(aes(color = Borough)) +
  xlab("Date by Months") + 
  ylab("Rate of rats per kiloton of waste")

p
```





```{r}
convertToShpDistrict <- function(com_district) {
  sapply(com_district, function(com_district) { 
  split = strsplit(com_district, " ")
  boro = case_when (str_to_lower(split[[1]][2]) == 'brooklyn' ~ 'BK',
                    str_to_lower(split[[1]][2]) == 'manhattan' ~ 'MN',
                    str_to_lower(split[[1]][2]) == 'queens' ~ 'QW',
                    str_to_lower(split[[1]][2]) == 'staten' ~ 'SI',
                    str_to_lower(split[[1]][2]) == 'bronx' ~ 'BX'
                    );

  ans <- paste(boro, split[[1]][1], sep="")

  return (ans)
  })
}
```


```{r}
full_tonnage <-read.csv("sanitation_data/dsny_full_tonnage.csv", stringsAsFactors = FALSE)
full_tonnage <- full_tonnage %>%
  mutate(district =  paste(full_tonnage$COMMUNITYDISTRICT, str_to_upper(full_tonnage$BOROUGH)))
      
```
```{r}
head(full_tonnage)
```

```{r}
ton_map <- full_tonnage %>%
  mutate(community_district = convertToShpDistrict(district)) %>% 
  group_by(community_district) %>%
  summarise(total_ton = sum(REFUSETONSCOLLECTED))

ton_map
```


```{r}
rat_map <- rat_data %>%
  mutate(community_district = convertToShpDistrict(Community.Board)) %>% 
  group_by(community_district) %>%
  tally()

rat_map
```




```{r}
# ton_col <- unique(full_tonnage[c("district")]) 
# ratcol <- unique(rat_data[c("Community.Board")]) %>%
```


```{r}
rat_borough <- rat_data %>% 
  group_by(Borough) %>%
  tally()

rat_borough
```


```{r}
ton_boro <- tonnage_data %>%
  group_by(BOROUGH) %>%
  summarise(total_ton = sum(REFUSETONSCOLLECTED))

ton_boro
```

```{r}
rat_ton <- left_join(rat_borough, ton_boro, by = c("Borough" = "BOROUGH"))
```
```{r}
rat <- ggplot(rat_ton, aes(y=n, x=Borough)) + 
    geom_bar(position="dodge", stat="identity")
rat
```
```{r}
ton <- ggplot(rat_ton, aes(y=total_ton, x=Borough)) + 
    geom_bar(position="dodge", stat="identity")
ton
```

```{r}
# dual y axis 

# A few constants
temperatureColor <- "#69b3a2"
priceColor <- rgb(0.2, 0.6, 0.9, 1)

f <- ggplot(rat_ton, aes(x=Borough)) +
  
  geom_bar( aes(y=n), stat='identity', fill=temperatureColor) + 
  geom_bar( aes(y=total_ton), stat='identity', fill=priceColor) +
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Number of Rat Sightings",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~ . + 10000000000000000, name="Metric Ton of Waste ")
  ) + 
  
  # theme_ipsum() +

  theme(
    axis.title.y = element_text(color = temperatureColor, size=13),
    axis.title.y.right = element_text(color = priceColor, size=13)
  ) +

  ggtitle("Rat Sightings and Sanitation Waste (Feb 2020 - Feb 2021)")
```

```{r}
f
```

















```{r}
nyc <- readOGR("sanitation_data/CommunityDistricts/.", "geo_export_d81daad1-2b49-44c3-81d4-72436a58def3")
```
```{r}
nyc_sp <- spTransform(nyc, CRS("+proj=longlat +datum=WGS84"))
```

```{r}
convertBoroCDToDistrict <- function(borocd) {
  sapply(borocd, function(borocd) { 
  boro_ch = as.character(borocd) 
  boro_n = substr(boro_ch, 1, 1)
  cd_n = substr(boro_ch, 2, 3)
  
  print(boro_ch)
  
  boro = case_when (boro_n == '1' ~ 'MN',
                    boro_n == '2' ~ 'BX',
                    boro_n == '3' ~ 'BK',
                    boro_n == '4' ~ 'QW',
                    boro_n == '5' ~ 'SI'
                    )
  
  # print(boro)

  ans <- paste(boro, cd_n, sep="")
  # print(ans)

  return (ans)
  })
}
```

```{r}
nyc_sp@data <- nyc_sp@data %>%
  mutate(community_district = convertBoroCDToDistrict(boro_cd))

nyc_sp@data
```
```{r}
nyc_sp@data <- left_join(nyc_sp@data, rat_map)
nyc_sp@data
```

```{r}
nyc_sp@data <- left_join(nyc_sp@data, ton_map) 
nyc_sp@data
```
```{r}
nyc_sp
```

```{r}
# ggplot() + 
#   geom_polygon(data = nyc_sp, aes(fill = n, x = ))
# library(geojsonio)
# spdf <- geojson_read("sanitation_data/DSNYSections/.", "DSNYSections.geojson", what = "sp")
# spdf
```
```{r}
tm_shape(nyc_sp) +
tm_fill("n", title = "Rat Sightings in Community Districts")
```

```{r}
tm_shape(nyc_sp) +
tm_fill("total_ton", title = "Tones of Waste and Rat Sightings by DSNY Districts")
```












```{r}
legend_creator = function(col.regions, xlab, ylab, nbins){
  bilegend = levelplot(matrix(1:(nbins * nbins), nrow = nbins),
                       axes = FALSE, col.regions = col.regions,
                       xlab = xlab, ylab = ylab,
                       cuts = 8, colorkey = FALSE, scales = list(draw = 0))
  bilegend
}
add_new_var = function(x, var1, var2, nbins, style = "quantile"){
  class1 = suppressWarnings(findCols(classIntervals(c(x[[var1]]), 
                                                    n = nbins, 
                                                    style = style)))
  
  class2 = suppressWarnings(findCols(classIntervals(c(x[[var2]]), 
                                                    n = nbins, 
                                                    style = style)))
  
  x$new_class = class1 + nbins * (class2 - 1)
  return(x)
}
```
```{r}
nyc_cd <- nyc_sp
```
```{r}
nyc_cd = add_new_var(nyc_cd, 
                     var1 = "n", 
                     var2 = "total_ton", 
                     nbins = 3)


```
used this for reference: https://github.com/mtennekes/tmap/issues/183#issuecomment-670554921 

```{r}
bilegend = legend_creator(stevens.pinkblue(n = 9), 
                          xlab = "rats", 
                          ylab = "total tonnes", 
                          nbins = 3)

bimap = tm_shape(nyc_cd) +
  tm_fill("new_class", style = "cat", palette = stevens.pinkblue(n = 9)) +
  tm_layout(legend.show = FALSE)

grid.newpage()
print(bimap)
vp = viewport(x = 0.25, y = 0.25, width = 0.25, height = 0.25)
pushViewport(vp)
print(bilegend, newpage = FALSE)
```

